### ISSUE TITLE
docs: what is the USP of this compared to lerna?

### ISSUE THREAD

**Issue by Xiphe** [xing/rlsr#3]
From reading the docs it's not clear to me why I should use this instead of lerna, what problems does this tool solve, that lerna doesn't?

**Comment by graphan** [comment]
The more accurate question would be what's the difference between rlsr and [lerna-semantic-release](https://github.com/atlassian/lerna-semantic-release)?

**Comment by Xiphe** [comment]
closing since this is pretty old and @graphan is right.
Lerna itself has no semantic release mechanics and https://github.com/atlassian/lerna-semantic-release is not really maintained anymore
